name: llm_omop
channels:
  - nvidia
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - nvidia/label/cuda-12.4.0::cuda
  - nvidia/label/cuda-12.4.0::cuda-nvcc
  - pandas=2.2.3
  - pip
  - numpy=2.0.2
  - sqlalchemy=2.0.41
  - ipympl
  - cython=3.0.11
  - loguru
  - jupyterlab
  - xlrd=2.0.1
  - scipy=1.15.3
  - scikit-learn=1.4.2
  - networkx=3.4.2
  - lxml=5.4.0
  - openpyxl=3.1.5
  - pyyaml=6.0.2
  - tornado=6.5.1
  - jinja2=3.1.6
  - matplotlib-inline=0.1.7
  - pip:
    - setuptools==65
    - transformers>=4.31.0
    - tqdm==4.67.1
    - wheel
    - joblib==1.5.1
    - pyodbc
    - torchserve
    - torch-model-archiver
    - torch-workflow-archiver
    - requests==2.32.3
    - captum==0.6.0
    - packaging==25.0
    - pynvml
    - ninja
    # torchserve's client
    - grpcio
    - protobuf
    - grpcio-tools
    - googleapis-common-protos
    - flask==3.1.1
    - flask-restful
    - lmdeploy
    - sglang
    # Core LLM_OMOP dependencies
    - instructor==1.8.3
    - openai==1.82.0
    - python-dotenv==1.1.0
    - ontogpt==1.0.13
    - linkml==1.9.2
    - linkml-runtime==1.9.2
    - linkml-owl==0.3.0
    - linkml-renderer==0.3.1
    - oaklib==0.6.22
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    # Medical NLP dependencies
    - medspacy==1.3.1
    - medspacy-quickumls==3.2
    - medspacy-unqlite==0.9.8
    - spacy==3.8.7
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    #- en-core-web-sm==3.8.0 can't have the models in my VA build (done after)
    # Knowledge graph and ontology dependencies
    - rdflib==7.1.4
    - rdflib-jsonld==0.6.1
    - rdflib-shim==1.0.3
    - pronto==2.7.0
    - fastobo==0.13.0
    - funowl==0.2.3
    - curies==0.10.19
    - prefixmaps==0.2.6
    - prefixcommons==0.1.12
    # OMOP and SSSOM dependencies
    - omop2owl-vocab==1.3.5
    - sssom==0.4.16
    - sssom-schema==1.0.0
    - semsql==0.4.0
    # Additional utilities
    - adeft==0.12.3
    - gilda==1.4.1
    - bioc==2.1
    - pystow==0.7.0
    - typing-extensions==4.13.2
    - annotated-types==0.7.0
    - cattrs==24.1.3
    - attrs==25.3.0
    - click==8.1.8
    - rich==13.9.4
    - typer==0.15.4
    - tenacity==9.1.2
    - httpx==0.28.1
    - httpcore==1.0.9
    - aiohttp==3.12.0
    - aiofiles==24.1.0
    - fastapi==0.115.12
    - uvicorn==0.34.2
    - starlette==0.46.2
    - sqlalchemy-utils==0.38.3
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - tzdata==2025.2
    - urllib3==1.26.20
    - certifi==2025.4.26
    - charset-normalizer==3.4.2
    - idna==3.10
    - six==1.17.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2025.4.1
    - referencing==0.36.2
    - rpds-py==0.25.1
    - jsonlines==4.0.0
    - beautifulsoup4==4.13.4
    - soupsieve==2.7
    - lark==1.2.2
    - nltk==3.9.1
    - regex==2024.11.6
    - tokenizers==0.21.1
    - tiktoken==0.9.0
    - huggingface-hub==0.32.0
    - filelock==3.18.0
    - fsspec==2025.5.1
    - litellm==1.71.1
    - aiohappyeyeballs==2.6.1
    - aiosignal==1.3.2
    - frozenlist==1.6.0
    - multidict==6.4.4
    - yarl==1.20.0
    - propcache==0.3.1
    - sniffio==1.3.1
    - anyio==4.9.0
    - h11==0.16.0
    - httpx-aiohttp==0.1.4
    - PyMuPDF==1.26.0
    - sparqlslurper==0.5.1
    - SPARQLWrapper==2.0.0
    - kgcl-rdflib==0.5.0
    - kgcl-schema==0.6.9
    - ols-client==0.1.4
    - ontoportal-client==0.0.4
    - PyShEx==0.8.1
    - PyShExC==0.9.1
    - ShExJSG==0.8.2
    - PyJSG==0.11.10
    - rfc3987==1.3.8
    - json-flattener==0.1.9
    - jsonasobj==1.3.1
    - jsonasobj2==1.0.4
    - pansql==0.0.1
    - diskcache==5.6.3
    - requests-cache==1.2.1
    - requests-toolbelt==1.0.0
    - url-normalize==2.2.1
    - cachier==3.1.2
    - portalocker==3.1.1
    - cloudpathlib==0.21.1
    - smart-open==7.1.0
    - boto3==1.38.23
    - botocore==1.38.23
    - s3transfer==0.13.0
    - jmespath==1.0.1
    - more-itertools==10.7.0
    - class-resolver==0.6.0
    - inflection==0.5.1
    - deprecation==2.1.0
    - Deprecated==1.2.18
    - validators==0.35.0
    - watchdog==6.0.0
    - ratelimit==2.2.1
    - graphviz==0.20.3
    - wasabi==1.1.3
    - confection==0.1.5
    - thinc==8.3.6
    - catalogue==2.0.10
    - srsly==2.5.1
    - murmurhash==1.0.13
    - cymem==2.0.11
    - preshed==3.0.10
    - blis==1.3.0
    - weasel==0.4.1
    - threadpoolctl==3.6.0
    - langcodes==3.5.0
    - language-data==1.3.0
    - marisa-trie==1.2.1
    - pysimstring==1.3.0
    - quicksectx==0.4.0
    - PyRuSH==1.0.9
    - PyFastNER==1.0.10
    - pysbd==0.3.4
    - intervaltree==3.1.0
    - sortedcontainers==2.4.0
    - eutils==0.6.0
    - roman-numerals-py==3.1.0
    - inflect==7.5.0
    - Unidecode==1.4.0
    - wikipedia==1.4.0
    - Wikipedia-API==0.8.1
    - docstring-parser==0.16
    - more-click==0.1.2
    - shellingham==1.5.4
    - ipykernel==6.29.5
    - ipython==9.2.0
    - ipywidgets==8.1.7
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.15
    - widgetsnbextension==4.0.14
    - comm==0.2.2
    - debugpy==1.8.14
    - nest-asyncio==1.6.0
    - psutil==7.0.0
    - pyzmq==26.4.0
    - traitlets==5.14.3
    - asttokens==3.0.0
    - decorator==5.2.1
    - executing==2.2.0
    - jedi==0.19.2
    - matplotlib-inline==0.1.7
    - parso==0.8.4
    - pexpect==4.9.0
    - prompt-toolkit==3.0.51
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - Pygments==2.19.1
    - stack-data==0.6.3
    - wcwidth==0.2.13
    - ipython-pygments-lexers==1.1.1
    - wrapt==1.17.2
    - typeguard==4.4.2
    - typing-inspection==0.4.1
    - jsonpointer==3.0.0
    - fqdn==1.5.1
    - isoduration==20.11.0
    - uri-template==1.3.0
    - webcolors==24.11.1
    - rfc3339-validator==0.1.4
    - arrow==1.3.0
    - types-python-dateutil==2.9.0.20250516
    - defusedxml==0.7.1
    - et-xmlfile==2.0.0
    - mdurl==0.1.2
    - markdown-it-py==3.0.0
    - MarkupSafe==3.0.2
    - itsdangerous==2.2.0
    - Werkzeug==3.1.3
    - blinker==1.9.0
    - flask-restx==1.3.0
    - aniso8601==10.0.1
    - pysolr==3.10.0
    - appdirs==1.4.4
    - distro==1.9.0
    - hf-xet==1.1.2
    - jiter==0.8.2
    - parse==1.20.2
    - dpath==2.2.0
    - ruamel.yaml==0.18.11
    - ruamel.yaml.clib==0.2.12
    - importlib-metadata==8.7.0
    - importlib-resources==6.5.2
    - zipp==3.21.0
    - pluggy==1.6.0
    - iniconfig==2.1.0
    - pytest==8.3.5
    - pytest-logging==2015.11.4
    - toml==0.10.2
    - docopt==0.6.2
    - chardet==5.2.0
    - ijson==3.4.0
    - imagesize==1.4.1
    - snowballstemmer==3.0.1
    - alabaster==1.0.0
    - babel==2.17.0
    - docutils==0.21.2
    - Sphinx==8.2.3
    - sphinx-click==6.0.0
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    - airium==0.2.6
    - antlr4-python3-runtime==4.9.3
    - bcp47==0.1.0
    - CFGraph==0.2.1
    - frontend==0.0.3
    - hbreader==0.9.1
    - isodate==0.7.2
    - ndex2==3.10.0
    - platformdirs==4.3.8
    - PyTrie==0.4.0
    - appnope==0.1.4
